name: Lua Build
on:     
  push:
    tags:
      - 'v*'
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: win32-ia32
          - os: windows-latest
            platform: win32-x64
          - os: ubuntu-18.04
            platform: linux-x64
          - os: macos-11
            platform: darwin-x64
          - os: macos-11
            platform: darwin-arm64
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/master
        submodules : recursive
        
    - name: Luamake
      uses: actboy168/setup-luamake@master

    - run: luamake -platform ${{ matrix.platform }}
      continue-on-error: true

    - name: Upload
      uses: actions/upload-artifact@master
      with: 
        name: runtime
        path: publish/runtime

  upload-release:
      name: Upload Release
      if: startsWith(github.ref, 'refs/tags/')
      needs: [compile]
      runs-on: [ubuntu-18.04]
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - name: Create release
          id: create_release
          uses: actions/create-release@master
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
            body: ${{ github.ref }}
            draft: false
            prerelease: true

        - name: Download Runtime
          uses: actions/download-artifact@v1.0.0
          with:
            name: runtime
            path: artifact/runtime

        - name: Zip Runtime
          uses: TheDoctor0/zip-release@v0.2.1
          with:
            filename: runtime.zip
            path: artifact/runtime
        
        - name: Upload Runtime
          uses: actions/upload-release-asset@v1.0.1
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: runtime.zip
            asset_name: runtime.zip
            asset_content_type: application/tar+gzip