name: build
on: push
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: win32-ia32
          - os: windows-latest
            platform: win32-x64
          - os: ubuntu-18.04
            platform: linux-x64
          - os: macos-11
            platform: darwin-x64
          - os: macos-11
            platform: darwin-arm64
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/master
        submodules : recursive
    - uses: actboy168/setup-luamake@master
    - run: luamake -platform ${{ matrix.platform }}
      continue-on-error: true
